### PR TITLE
change input autosize to textarea autosize

### PR DESCRIPTION
**Pull request by baoalvin1**
When you write a lengthy comment in smolt it goes off the screen, I imported an autosizing text area and updated the styles to match the original styling. Now when typing it will automatically move to the next line.

### CODE REVIEW

**Comment by migueldlr** [comment]
I like it! Do you think there's a way to fit the input so the point value and delete button still appear inline when the comment is less than the width of the box?

image

One idea I have would be that when the text is too long, we hide the overflow when the text box isn't focused, then switch to a larger textbox when it is.

**Comment by baoalvin1** [comment]
Yeah I can look into that, currently the textarea width is set at 100%, I can play around with it and let you know what I find!

**Comment by baoalvin1** [comment]
I fixed the inline issue but sometimes when the window becomes a certain size the points and the delete button end up on the same side. I'll look into hiding the overflow next.

**Comment by baoalvin1** [comment]
Just implemented hiding the overflow let me know what you think!

**Comment by migueldlr** [comment]
Sorry to nitpick, but could you make the point value/delete button align at the top of the overflow text box rather than the bottom?

image

**Comment by baoalvin1** [comment]
The score and the delete button align to the top now!

**Comment by migueldlr** [comment]
Looks great! Thanks!

**Pull request merged**
